spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      claim-settlement-topic: claim-settlement-topic
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema:
          registry:
            url: "http://127.0.0.1:8081"
